<a href="https://colab.research.google.com/github/ashishdwivedi2410/Data-Analysis-course/blob/main/CHAPTER_4_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [12]:
pip install numpy

In [13]:
import numpy as np

## Create array using numpy
## Create a 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [17]:
#reshape
arr11=np.array([1,2,3,4,5])
arr11.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [14]:
## Create a 2d array
arr2= np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


In [16]:
#reshape
arr3= np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [26]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#attributes of numpy
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Array:",arr)
print("Shape:",arr.shape)
print("Numbers of Dimension:",arr.ndim)
print("Numbers of Dimension:",arr.size)
print("Data type:\n",arr.dtype)
print("Item Size",arr.itemsize)

Array: [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Numbers of Dimension: 2
Numbers of Dimension: 8
Data type:
 int64
Item Size 8


In [34]:
# Numpy vectorized Opertion
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# Element Wise Addition
print(arr1+arr2)

# Element Wise Substract
print(arr1-arr2)

# Element Wise Multiplcation
print(arr1*arr2)

# Element Wise Division
print(arr1/arr2)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [36]:
# Universal Function
arr=np.array([1,2,3,4,5])

#sqare root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sin
print(np.sin(arr))

#cos
print(np.cos(arr))
#log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
#array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr[0][0]

np.int64(1)

In [40]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
# modify array element
arr[0,0]=100
print(arr)

In [44]:
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
### stastical concept --Normalization
## to have a mean of 0 and standard devation of 1

data = np.array([1,2,3,4,5])

#calculate the mean and standard devation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data-mean)/std_dev

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:",mean)

#standard deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

#variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [47]:
## Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

# **Pandas-DataFrame And Series**